### ISSUE TITLE
about your data

### ISSUE THREAD

**Issue by Xuelei-Dai** [adamh-broad/single_cell_intestine#2]

**Comment by adamh-broad** [comment]
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE92332

**Comment by Xuelei-Dai** [comment]
thanks,
I get it.


On 7/9/2018 05:07，adamh-broad<notifications@github.com> wrote：
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE92332
