### ISSUE TITLE
10X raw data

### ISSUE THREAD

**Issue by jan-glx** [adamh-broad/single_cell_intestine#3]
Hi Adam,

The geo records for the 10X samples (`GSM2836573` - `GSM2839471`) , e.g. [this one](https://www.ebi.ac.uk/ena/data/view/SRR6254366), seem to contain raw data for only one read. I would expect two fastq files, one for read 1 (cell barcode +UMI) and one for read 2 (mRNA). Am I missing something?

best regards,
Jan

**Comment by adamh-broad** [comment]
Hi Jan,

I’m sorry for the confusion. The accessions for the 10X samples contain only a genome-mapped BAM file (generated by CellRanger). If you need fastqs 10X provides a tool that can extract the various read types you allude to into fastqs:
https://support.10xgenomics.com/docs/bamtofastq

Let me know if you have questions!

Best,
adam

**Comment by jan-glx** [comment]
Thanks for the quick reply, Adam,
that was very helpful. I guess GEO/NCBI/ENA converted the submitted bam files back to fastq files without preserving the read information (cbc). 
In case s.o. else was looking for it: the bam file can be downloaded here:
https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR6237197
https://sra-download.ncbi.nlm.nih.gov/traces/sra53/SRZ/006254/SRR6254381/FAE_Control_Rep2.bam

thanks again,
Jan
